name: 🚀 Auto Deploy to FTP (spravato)

on:
  push:
    branches:
      - main  # Deploy only when main branch is pushed

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📤 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp                     # Try ftps if ftp fails
          port: 21
          server-dir: /dnd.appwebdemo.pro/  # Change if your root is different
          local-dir: ./                     # Root of your repo
          passive: false                    # Try true if false doesn't work
          retry: true                       # Enable retry if connection drops
          exclude: |
            **/.git*
            .git/
            **/.vscode*
            **/tests/**
            **/storage/logs/**
